### PR TITLE
Enable OAS 3 support. fixes #9

### LINKED ISSUE #9: Support OAS3

### PR DESCRIPTION
**Pull request by Emilio-Pega**
Add OAS 3 support.

Switch the command line to use the OAS 3 parser & model.  According to the [swagger-parser](https://github.com/swagger-api/swagger-parser) documentation, the parser is backwards compatible with v2 of the spec.

So what happens is that we load all the swagger files (spec and coverage) using the `OpenAPIParser`.
* if the file is a v2 file, then the parser automatically converts it to a v3 model
* handles both yaml & json formats

Almost all of the other changes are ones that convert the CLI logic to use the v3 model classes.

One difficult part was dealing with v2 BodyParam & FormParam.  The v3 spec does not have that type of param, instead these are translated into the operation's requestBody (see https://swagger.io/docs/specification/describing-request-body/).

Tests check both v3 and v2 formats.

### CODE REVIEW

**Comment by viclovsky** [comment]
Hello, @Emilio-Pega  
Thanks a lot for your PR. There are a lot of changes in the PR, thus I need some time to test it. If everything is fine, I'll release new version 2.0.0.

**Review by viclovsky — APPROVED** [review]
@Emilio-Pega I did some tests locally and the result is good. Thanks for your contribution. 👍

**Comment by viclovsky** [comment]
Hello, @Emilio-Pega  
Right after I have merged your PR, I have found  that "Condition name" is NULL for properties for OpenAPi v3. Have no idea what's wrong, could you  look at it?

изображение

**Comment by Emilio-Pega** [comment]
Sure I'll take a look on Monday

**Comment by Emilio-Pega** [comment]
Looks like, for some reason, the Shchema name is `null` here: https://github.com/viclovsky/swagger-coverage/blob/master/swagger-coverage-commandline/src/main/java/com/github/viclovsky/swagger/coverage/core/rule/body/PropertyNotEmptyRule.java#L14

will keep digging

**Comment by Emilio-Pega** [comment]
This should fix it 

https://github.com/viclovsky/swagger-coverage/pull/78

**Pull request merged**
